---
title: "Mesh construction"
author: "Dave Holtschlag"
date: "March 23, 2018"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```

## Load INLA Library

```{r load_inla}
# Installed March 23, 2018
# source('http://www.math.ntnu.no/inla/givemeINLA-testing.R')
# Uncomment the line below to upgrade inla install
install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
inla.upgrade(testing=TRUE)
library('INLA')
library(geoR)

```

```{r}
(lkhat <- attr(nllf(ores$par, matrix(1,n),
y1, as.matrix(dmat)), 'param'))


```

## Demo in Journal of Statistical Software
Bayesian Spatial Modelling with R-INLA by Finn Lindgren, and Havard Rue

```{r pressure, echo=FALSE}
m = 50
points = matrix(runif(m * 2), m, 2)
mesh = inla.mesh.2d(loc = points, cutoff = c(0.1, 0.4), 
                    offset = c(0.1, 0.4), max.edge = c(0.05, 0.5))
```

```{r tutorial1}
library('INLA')
n       <- 200; 
set.seed(123)
pts <- cbind(s1=sample(1:n/n-0.5/n)^2, s2=sample(1:n/n-0.5/n)^2)

# Lower triangular matrix of distances
dmat    <- dist(pts)

beta0   <- 10; sigma2e <- 0.3; sigma2x <- 5; kappa <- 7; nu <- 1

mcor       <- as.matrix(2^(1-nu)*(kappa*dmat)^nu* besselK(dmat*kappa,nu)/gamma(nu))
diag(mcor) <- 1; mcov <- sigma2e*diag(n) + sigma2x*mcor

L <- chol(mcov); set.seed(234); y1 <- beta0 + drop(rnorm(n)%*%L)

par(mar=c(3,3,1,1), mgp=c(1.7, 0.7, 0), las=1)
plot(pts, asp=1, xlim=c(0,1.2), cex=y1/10)
q <- quantile(y1, 0:5/5)
legend('topright', format(q, dig=2), pch=1, pt.cex=q/10)

```


```{r f_nullf}

nllf <- function(pars, ff, y, m) {
m <- 2^(1-pars[3])*(pars[2]*m)^pars[3]*
besselK(m*pars[2],pars[3])/gamma(pars[3])
diag(m) <- 1 + pars[1]
m <- chol(m)
ldet.5 <- sum(log(diag(m)))
m <- chol2inv(m)
beta <- solve(crossprod(ff, m)%*%ff,
crossprod(ff, m)%*%y)
z <- y-ff%*%beta
s2x.hat <- mean(crossprod(m,z)*z)
res <- ldet.5 + nrow(m)*(1+log(2*pi*s2x.hat))/2
attr(res, 'param') <- ### to return the parameters together
c(beta=beta, s2e=pars[1]*s2x.hat,
s2x=s2x.hat, kappa=pars[2], nu=pars[3])
return(res)
}
```


```{r}
(nllf(c(sigma2e/sigma2x, kappa, nu), matrix(1,n), y1, as.matrix(dmat)))

(nllf(c(0, kappa, nu), matrix(1,n), y1, as.matrix(dmat)))

(ores <- optim(c(sigma2e/sigma2x, kappa, nu), nllf, hessian=TRUE,
ff=matrix(1,n), y=y1, m=as.matrix(dmat),
method='L-BFGS-B', lower=rep(1e-5,3)))$par

(lkhat <- attr(nllf(ores$par, matrix(1,n),
y1, as.matrix(dmat)), 'param'))
```


```{r}
(lkhat <- attr(nllf(ores$par, matrix(1,n), y1, as.matrix(dmat)), 'param'))

require(geoR); set.seed(234)
grf1 <- grf(grid=pts, cov.pars=c(sigma2x, 1/kappa), mean=beta0, nugget=sigma2e, 
            kappa=nu, messages=FALSE)

(g1res <- likfit(grf1, ini=c(sigma2x, 1/kappa), messages=FALSE, nugget=sigma2e, 
                 kappa=nu, fix.kappa=FALSE))

(fit.l <- likfit(grf1, ini.cov.pars=c(sigma2x, 1/kappa), nugget=sigma2e, 
                 kappa=1, messages=FALSE))
```


```{r }
data(SPDEtoy)
coords <- as.matrix(SPDEtoy[,1:2]) ; p5 <- coords[1:5,]

pl.dom <- cbind(c(0,1,1,0.7,0), c(0,0,0.7,1,1))

m1 <- inla.mesh.2d(p5, max.edge=c(0.5, 0.5))
m2 <- inla.mesh.2d(p5, max.edge=c(0.5, 0.5), cutoff=0.1)
m3 <- inla.mesh.2d(p5, max.edge=c(0.1, 0.5), cutoff=0.1)
m4 <- inla.mesh.2d(p5, max.edge=c(0.1, 0.5), offset=c(0,-0.65))

m5 <- inla.mesh.2d(p5, pl.dom, max.edge=c(0.3, 0.5), offset=c(0.03, 0.5))
m6 <- inla.mesh.2d(p5, pl.dom, max.edge=c(0.3, 0.5), offset=c(0.03, 0.5), cutoff=0.1)
m7 <- inla.mesh.2d(p5, pl.dom, max.edge=c(0.3, 0.5), n=5, offset=c(.05,.1))
m8 <- inla.mesh.2d(p5, pl.dom, max.edge=c(.3, 0.5), n=7, offset=c(.01,.3))
m9 <- inla.mesh.2d(p5, pl.dom, max.edge=c(.3, 0.5), n=4, offset=c(.05,.3))


```